First commit

diff --git a/target/dist/mush b/target/dist/mush
--- a/target/dist/mush
+++ b/target/dist/mush
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 ## BP010: Release metadata
 ## @build_type: bin
-## @build_date: 2023-11-02T01:18:48Z
+## @build_date: 2023-11-02T14:19:10Z
 set -e
 if ! declare -F "extern" > /dev/null; then
   extern() {
@@ -1158,7 +1158,7 @@ console_hint() {
 #!/usr/bin/env bash
 ## BP010: Release metadata
 ## @build_type: lib
-## @build_date: 2023-11-02T01:18:48Z
+## @build_date: 2023-11-02T14:19:08Z
 set -e
 if ! declare -F "extern" > /dev/null; then
   extern() {
@@ -2370,6 +2370,42 @@ process_dev_dependencies_build() {
     fi
   done
 }
+#!/usr/bin/env bash
+## BP010: Release metadata
+## @build_type: lib
+## @build_date: 2023-11-02T14:19:10Z
+set -e
+if ! declare -F "extern" > /dev/null; then
+  extern() {
+    extern=$1
+  }
+fi
+if ! declare -F "legacy" > /dev/null; then
+  legacy() {
+    legacy=$1
+  }
+fi
+if ! declare -F "module" > /dev/null; then
+  module() {
+    module=$1
+  }
+fi
+if ! declare -F "public" > /dev/null; then
+  public() {
+    public=$1
+  }
+fi
+if ! declare -F "use" > /dev/null; then
+  use() {
+    use=$1
+  }
+fi
+if ! declare -F "embed" > /dev/null; then
+  embed() {
+    embed=$1
+  }
+fi
+## BP004: Compile the entrypoint
 # FATAL
 # ERROR
 # WARNING
@@ -2405,6 +2441,12 @@ console_status() {
 }
 console_error() {
   echo -e "${ESCAPE}[1;31merror${ESCAPE}[0m: $1" >&2
+}
+console_error_code() {
+  echo -e "${ESCAPE}[1;31merror[$1]${ESCAPE}[1;39m: $2${ESCAPE}[0m" >&2
+}
+console_hint() {
+  echo -e "${ESCAPE}[1;39m$1${ESCAPE}[0m" >&2
 }
 console_print() {
   if [ -z "${QUIET}" ]; then
