First commit

diff --git a/target/dist/mush b/target/dist/mush
--- a/target/dist/mush
+++ b/target/dist/mush
@@ -416,7 +416,7 @@ debug_2022() {
 legacy() {
   legacy_file=target/debug/legacy/$1.sh
   if [ ! -f "$legacy_file" ]; then
-    error "errrore"
+    echo "File not found '${legacy_file}', type 'mush build' to recover this problem." >&2
     exit 101
   fi
   source "${legacy_file}"
@@ -452,10 +452,6 @@ use() {
 embed() {
   local module_file=src/$MUSH_RUNTIME_MODULE/$1.sh
   eval "$(embed_file $1 $module_file)"
-}
-
-error() {
-  echo "$1"
 }
 EOF
 }
