Development Commit

diff --git a/target/debug/mush b/target/debug/mush
--- a/target/debug/mush
+++ b/target/debug/mush
@@ -1,12 +1,20 @@
 #!/usr/bin/env bash
 set -e
 
-# @build_section: BS002 - Package and debug variables 
+# @section_code: FS002
+# @section_name: file-meta
+# @file_path: target/debug/mush
+# @file_type: build-entrypoint
+
+# @section_code: FS003
+# @section_name: debug-entrypoint-init
+
+# @build_section: BS002 - Package and debug variables
 MUSH_PACKAGE_NAME="mush"
 MUSH_TARGET_FILE="target/debug/mush"
 MUSH_TARGET_PATH="target/debug"
 MUSH_DEBUG_TARGET_FILE="$(realpath "$0")"
-MUSH_DEBUG_PATH="$(realpath "$(dirname "$0")/../..")"
+MUSH_DEBUG_PATH="/home/francesco/Develop/Javanile/mush"
 
 # @build_section: BS003 - Embedding debug api
 debug() {
@@ -113,8 +121,56 @@ debug() {
     *)
   esac
 }
+mush_api_2022_embed() {
+  local module_name
+  local module_file
+  local inject_type
+  local inject_name
+  local inject_file
+  local inject_data
+  module_name=$1
+  module_file=$2
+  echo "${module_name}() {"
+  echo "  if [ -z \"\$1\" ]; then"
+  echo "    cat <<'EMBED'"
+  #cat "$module_file" | tr -s '\n'
+  sed '/^[[:space:]]*$/d' "${module_file}"
+  echo "EMBED"
+  echo "  else"
+  echo "    case \"\$1\" in"
+  grep -n '^inject [a-z][a-z]* [a-zA-Z0-9][a-zA-Z0-9_\.]*$' "${module_file}" | while read -r line; do
+    inject_type=$(echo "${line#*inject}" | awk '{print $1}')
+    inject_name=$(echo "${line#*inject}" | awk '{print $2}')
+    echo "      ${inject_name})"
+    case "${inject_type}" in
+      file)
+        inject_file="$(dirname "${module_file}")/${inject_name}"
+        echo "        cat <<'EMBED'"
+        cat "$inject_file"
+        echo ""
+        echo "EMBED"
+        ;;
+      env)
+        eval inject_data="\$$inject_name"
+        echo "        echo \"$inject_data\""
+        ;;
+      *)
+        echo "ERROR: Unknown inject type '${inject_type}' in line '${line}'"
+        exit 101
+        ;;
+    esac
+    echo "        ;;"
+  done
+  echo "      *)"
+  echo "        echo \"${inject_type}: ${inject_name}\""
+  echo "        ;;"
+  echo "    esac"
+  echo "  fi"
+  echo "}"
+}
 
 # @build_section: BS001 - Appending entrypoint to debug build
 debug init
+# @build_section: BS001 - Appending entrypoint to debug build
 debug file "${MUSH_DEBUG_PATH}/src/main.sh"
 main "$@"
